# Site settings
title: DuduLili
header-img: img/home-bg.jpg
email: dudulili2014@gmail.com
description: "路在远方"
baseurl: ""
url: "http://dudulili.com"
twitter_username: LiGQLi
github_username:  dudulili
facebook_username:  liguoqing

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]


comments :
   provider : duoshuo
    duoshuo : 
   shortname : dudulili

# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "DuduLili"
      header-img: "img/post-bg-01.jpg" # We don't want posts without a header image, that whould mean white on white
